use_frameworks!

platform :ios, '9.0'

target 'ButtonClickStyle_Example' do
  pod 'ButtonClickStyle', :path => '../'

  target 'ButtonClickStyle_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
